/** Hindi UI copy for the blog experience (navigation may stay English). */
export const hi = {
  blogEyebrow: "मालाणी ब्लॉग",
  blogTitle: "सरकारी नौकरी और भर्ती अपडेट",
  blogSubtitle:
    "सरकारी नौकरियों, भर्ती फॉर्म, परीक्षा तिथियों, एडमिट कार्ड और रिजल्ट से जुड़ी हर महत्वपूर्ण अपडेट अब सबसे पहले पाएँ — सरल हिंदी में।",
  searchPlaceholder: "लेख खोजें…",
  filterAll: "सभी",
  filterInsights: "जानकारी",
  filterUpdates: "अपडेट",
  filterCommunity: "समुदाय",
  tabLatest: "नवीनतम",
  tabTrending: "लोकप्रिय",
  trendingTitle: "इस समय चर्चा में",
  trendingDesc: "पाठकों द्वारा सबसे अधिक पसंद किए गए लेख।",
  libraryEyebrow: "संग्रह",
  libraryLatest: "नवीनतम लेख",
  libraryTrending: "लोकप्रिय लेख",
  libraryLatestDesc: "ताज़ा लेख — समयानुसार।",
  libraryTrendingDesc: "पसंद और चर्चा के आधार पर क्रमबद्ध।",
  emptyNoPosts: "अभी कोई लेख नहीं",
  emptyNoPostsDesc: "नए लेख यहाँ दिखेंगे, फिर से चेक करें।",
  emptyNoMatch: "कोई परिणाम नहीं",
  emptyNoMatchDesc: "कृपया शब्द बदलकर खोजें या फ़िल्टर हटाएँ।",
  resetFilters: "फ़िल्टर रीसेट करें",
  readArticle: "और पढ़ें",
  minRead: "मिनट पढ़ें",
  likes: "पसंद",
  comments: "टिप्पणियाँ",
  article: "लेख",
  featured: "विशेष",
  noCover: "कोई छवि नहीं",
  backToBlog: "ब्लॉग पर वापस",
  writtenBy: "लेखक",
  contributorLine: "मालाणी ब्लॉग योगदानकर्ता",
  discussion: "चर्चा",
  discussionCount: "टिप्पणियाँ",
  commentPlaceholder: "अपनी राय लिखें…",
  postComment: "टिप्पणी पोस्ट करें",
  posting: "पोस्ट हो रहा है…",
  signInToComment: "चर्चा में शामिल होने के लिए साइन इन करें।",
  signIn: "साइन इन",
  noCommentsYet: "अभी कोई टिप्पणी नहीं — आप शुरुआत करें।",
  likeLabel: "पसंद करें",
  share: "साझा करें",
  relatedTitle: "और पढ़ें",
  relatedDesc: "आपको ये लेख भी पसंद आ सकते हैं।",
  read: "पढ़ें",
  notFound: "लेख नहीं मिला",
  notFoundDesc: "यह लिंक हटा दिया गया हो सकता है या गलत है।",
  errorLoad: "लेख लोड नहीं हो सका।",
  homeFeaturedEyebrow: "ब्लॉग",
  homeFeaturedTitle: "नवीनतम लेख",
  homeFeaturedSubtitle: "मालाणी बाड़मेर की ताज़ा जानकारी और कहानियाँ।",
  homeReadMore: "और पढ़ें",
  adminDashTitle: "सामग्री डैशबोर्ड",
  adminTitle: "ब्लॉग प्रबंधन",
  adminSubtitle: "सार्वजनिक ब्लॉग के लिए लेख बनाएँ, संपादित करें व प्रकाशित करें।",
  newPost: "नया लेख",
  statPosts: "कुल लेख",
  statComments: "टिप्पणियाँ",
  statLikes: "पसंद",
  allPosts: "सभी लेख",
  cover: "कवर",
  titleCol: "शीर्षक",
  authorCol: "लेखक",
  publishedCol: "प्रकाशित",
  actionsCol: "क्रियाएँ",
  preview: "पूर्वावलोकन",
  edit: "संपादन",
  delete: "हटाएँ",
  noPostsAdmin: "अभी कोई लेख नहीं।",
  writeFirst: "पहला लेख लिखें",
  sheetCreateTitle: "नया लेख",
  sheetEditTitle: "लेख संपादित करें",
  sheetCreateDesc: "नया लेख प्रकाशित करें।",
  sheetEditDesc: "शीर्षक, कवर व सामग्री अपडेट करें — तुरंत लाइव हो जाएगा।",
  fieldTitle: "शीर्षक",
  fieldCoverUrl: "कवर छवि URL",
  fieldContent: "सामग्री",
  tabEditor: "संपादक",
  tabPreview: "पूर्वावलोकन",
  cancel: "रद्द करें",
  save: "सहेजें",
  publish: "प्रकाशित करें",
  saving: "सहेजा जा रहा है…",
  deleteConfirmTitle: "यह लेख हटाएँ?",
  deleteConfirmDesc:
    "लेख स्थायी रूप से हट जाएगा। डेटाबेस नियमों के अनुसार टिप्पणियाँ व पसंद भी प्रभावित हो सकती हैं।",
  deleteConfirm: "हटाएँ",
  noAccess: "आपके पास प्रशासन अनुमति नहीं है।",
  goBlog: "ब्लॉग पर जाएँ",
  toastSignInLike: "पसंद करने के लिए साइन इन करें।",
  toastThanksLike: "धन्यवाद!",
  toastCommentOk: "टिप्पणी पोस्ट हो गई।",
  toastLoadFail: "लेख लोड नहीं हो सका।",
  toastLinkCopied: "लिंक कॉपी हो गया।",
  toastPostSaved: "लेख सहेज लिया गया।",
  toastPostPublished: "लेख प्रकाशित हो गया।",
  toastPostRemoved: "लेख हटा दिया गया।",
} as const;
